### ISSUE TITLE
One pontential issue in win_primal.m

### ISSUE THREAD

**Issue by zexiangliu** [pettni/abstr-refinement#11]
https://github.com/pettni/abstr-refinement/blob/685cf194a2b7d794fe09ba577fb87d04cd7ef8d8/abstr-ref/%40TransSyst/win_primal.m#L72-L73

Hi Peter (@pettni) ,
I am confused about the two lines above. Why don't we need to save the controllers returned by Pre and PGPre here? There is usually a gap between Z and V. I thought that the controller for Pre(V) might be contained by the controller of win_intermediate in the next few lines. But today I encounter some issues when executing the controller returned by the `win_primal`, which I think might be relevant to my question here. Could you please help me find the answer?

Thank you,
Zexiang

**Comment by pettni** [comment]
I think you are right; these controllers should be saved and included in the overall controller. Could you provide a small example where the controller fails?

**Comment by zexiangliu** [comment]
I synthesized a controller for the type of spec `[ ] A && <>[ ] B`. Let's say the initial state is the state `62`. (`62` doesn't satisfy B.)  `cont(62)` then returns a list of actions `18,19,20,21`. But `62--18-->62` is one transition in the abstraction, which means that the system could be stuck at state `62` if we keep using the action `18`, which is suggested by the synthesized controller. 

By looking into the `win_primal`, I found that state `62` is included in the winning set due to the two lines above, exactly after the `win_primal` called the `win_intermediate` at the 6th time and before it called `win_intermediate` at the 7th time. The actions for `62` suggested by the `Pre` operator is only `20,21`, but the controller from the 7th call of `win_intermediate` suggests actions `18, 19, 20, 21`.

I can provide the code for this example if you want more details.

**Comment by pettni** [comment]
What would be most useful is if you could extract a minimal example that exhibits this problem that we can include as a test, similar to what is here: https://github.com/pettni/abstr-refinement/blob/master/tests/test_controller.m

In general the controller code has very few tests and there are probably more issues like the one you encountered, so more tests are always welcome.

**Comment by zexiangliu** [comment]
I think this one can show the issue.
```
ts = TransSyst(2,3);
s1 = [1,2,2];
a =  [1,2,3];
s2 = [1,1,2];

ts.add_transition(s1,s2,a);
ts.trans_array_enable();

B_list = 1;
[W, ~, cont] = win_primal(ts, [], B_list, [], 'exists', 'forall');

% 3 shouldn't be a control input for state 2
assert(~ismember(3, cont(2)));
```

**Comment by pettni** [comment]
Thanks for the testcase. I added it as a test and pushed a fix. Let me know if it solves your original problem.

**Comment by zexiangliu** [comment]
The updated code solved my original problem.
Thanks for the fix!
