### ISSUE TITLE
problem with plotting

### ISSUE THREAD

**Issue by necozay** [pettni/abstr-refinement#2]
```
plot(part.cell_list([]))
```

fails with the error:

```
Error using  > 
Not enough input arguments.

Error in Rec/plot (line 51)
    if rec.dim>3
```

Essentially, `plot(part)` fails when there is no part with empty AP. I'll post an update if I can fix it.

**Comment by necozay** [comment]
I have a small temporary fix that I will push soon.

**Comment by pettni** [comment]
Ah I just tried to push one. But I can’t test it because my Matlab seems broken after an OS upgrade and I can’t run it remotely either.

Petter

**Comment by pettni** [comment]
Current behavior is as follows:
```
>> part = Partition(Rec([0 0; 1 1]));
>> plot(part)    # shows domain in gray
>> plot(part.cell_list([]))
Warning: tried to plot nonexistent cell
```
