### ISSUE TITLE
update_progress_group is incomplete

### ISSUE THREAD

**Issue by necozay** [pettni/abstr-refinement#3]
It only implements the inheritance part but does not take advantage of the possibility of new progress groups emerging after partitioning.

**Comment by pettni** [comment]
This is obsolete with the removal of `update_progress_group`. The new examples search for transient sets up front, and then detect progress groups in these sets. The relevant code is [here](https://github.com/pettni/abstr-refinement/blob/master/abstr-ref/%40Partition/split_cell.m#L214).
