### ISSUE TITLE
Possible issues in 'win_eventually_or_persistence.m' and 'Controller.m'

### ISSUE THREAD

**Issue by zexiangliu** [pettni/abstr-refinement#5]
'win_eventually_or_peresistence.m':
1.  There is no values assigned to output 'C'.
2.  Line 17,18,27,28: the index seems to be 'end+1' instead of  'end'. Otherwise, 'Vlist' and 'Klist' are initialized as empty matrices, where the index 'end' is unavailable.

'Controller.m':
1. A error appears when calling 'get_input'and the method visits a sub-controller corresponding to a progress group. I guess the reason is that the set V and an empty controller is always added as the first term  when the sub-controller for progress group is generated.
2. Line 75 in 'Controller.m': why not directly search the sets containing that state and find out the one with smallest number instead of using the one before current ('bottom_cnt.mem_var-1') ?

**Comment by pettni** [comment]
Thanks, feel free to submit a pull request, preferably along with tests corresponding to the fixes. There are probably more quirks related to controllers and candidate sets in the "dual" algorithms as I didn't use these except for winning set computations.

Regarding Line 75 in `Controller.m`, implementing that change can potentially speed up time until reach.

**Comment by pettni** [comment]
Closed with #6
