### ISSUE TITLE
bug in win_dual

### ISSUE THREAD

**Issue by zexiangliu** [pettni/abstr-refinement#9]
https://github.com/pettni/abstr-refinement/blob/d6aa68810a5c10ad0f14b5248123d2ce3d23ae29/abstr-ref/%40TransSyst/win_dual.m#L39

The current `pre` function only takes boolean values as its `quant` inputs. For the line above, 'forall' will be interpreted as `true`, that is 'exists', in `pre`. 

Not sure for this line the 'forall' is a typo of 'exists', or should be replaced with `false`.

**Comment by pettni** [comment]
Pretty sure that should be `false`, I pushed a fix for it. Will leave this open for a bit in case somebody disagrees
